Module12 task1
htmlacademy-javascript/2049181-kekstagram-26 pull request #10
Opened 2022-07-19 11:32 UTC by webgolub

2022-07-19 16:57 UTC, AlexMasterov requested changes

2022-07-19 16:57 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7d14989f6e5488f9b86050babdcf6ed2ef70316e/js/filter.js#L12-L17
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7d14989f6e5488f9b86050babdcf6ed2ef70316e/js/filter.js#L20-L25
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7d14989f6e5488f9b86050babdcf6ed2ef70316e/js/filter.js#L28-L33
</details>

[`Д 14`](https://up.htmlacademy.ru/javascript/26/criteries#d14)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2022-07-19 16:57 UTC, AlexMasterov commented on js/filter.js
> +  return filteredPictures;
<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7d14989f6e5488f9b86050babdcf6ed2ef70316e/js/filter.js#L40
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7d14989f6e5488f9b86050babdcf6ed2ef70316e/js/filter.js#L55
</details>

В одном случае функция с названием `filter`Pictures вернет прежний массив, а не копию.

2022-07-19 16:57 UTC, AlexMasterov commented on js/picture.js
> +  picturesContainer.append(...pictures.map(renderThumbnail));
Функция `renderPictures` и _удаляет_ и _добавляет_, причем первое делает _неявно_.

2022-07-19 16:57 UTC, AlexMasterov commented on js/util.js
> +function debounce (callback, timeoutDelay = DEBOUNCE_DEFAULT_TIMEOUT) {
`function`

[`Д 5`](https://up.htmlacademy.ru/javascript/26/criteries#d5)
> Все функции объявлены единообразно

> При объявлении функций используются _стрелочные_ функции

2022-07-19 16:57 UTC, AlexMasterov commented on js/util.js
> +    timeoutId = setTimeout(() => callback.apply(this, rest), timeoutDelay);
timeoutId = setTimeout(() => callback.`apply`(`this`, rest), timeoutDelay);

🤔

```diff
- timeoutId = setTimeout(() => callback.apply(this, rest), timeoutDelay);
+ timeoutId = setTimeout(callback, timeoutDelay, rest);
```

2022-07-19 16:57 UTC, AlexMasterov commented on js/main.js
<details>
<summary>Проблема</summary>


![image](https://user-images.githubusercontent.com/700213/179805308-468b4c94-71d6-4fe2-95a1-55b827458dc1.png)

```
Uncaught TypeError: filterChangeCallback is not a function
    at HTMLElement.filterButtonClickHandler (filter.js:36:3)
```
</details>

Если данные не загрузились, то можно кликать по невидимым кнопка фильтрации, вызывая ошибки.

Б2

2022-07-19 16:57 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7d14989f6e5488f9b86050babdcf6ed2ef70316e/js/filter.js#L12-L13
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7d14989f6e5488f9b86050babdcf6ed2ef70316e/js/filter.js#L20-L21
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7d14989f6e5488f9b86050babdcf6ed2ef70316e/js/filter.js#L28-L29
</details>

На защите проекта могут придраться к строкам с `id`.

Б7, ~Д19

> На JS3 этот случай притянули к "магическим константам", что неверно, но для замечаний годится

**JS3**-Д5
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа

<details>
<summary>Пример</summary>

![image](https://user-images.githubusercontent.com/700213/179806604-1085fe50-b299-4308-987d-a466f18e2407.png)
![image](https://user-images.githubusercontent.com/700213/179806642-527f87d7-8091-4332-af91-19836d27f718.png)
</details>

2022-07-19 18:36 UTC, AlexMasterov commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
Эту функция следует перенести в отдельный модуль и убрать из неё _неявный_ побочный эффект с удалением класса в DOM.

2022-07-19 18:38 UTC, AlexMasterov commented on js/main.js
> +  renderPictures(filterPictures(pictures));
renderPictures(`filterPictures(pictures)`);

Вместо этого следует сделать функцию для включения (показа) панели фильтров.

2022-07-19 18:41 UTC, AlexMasterov commented on js/picture.js
> +  }
```js
// util.js
const removeElement = (element) => {
  element.remove();
};
```
```js
// picture.js
picturesContainer.querySelectorAll('.picture').forEach(removeElement);
```

2022-07-19 18:44 UTC, AlexMasterov commented on js/filter.js
> +        selectedFilterButton = evt.target;
Хранение названия фильтра и тем более элемента — избыточно.

2022-07-20 12:08 UTC, webgolub commented on js/filter.js
> +        selectedFilterButton = evt.target;
Я абсолютно не понимаю как это сделать. С примером со словарём-объектом в телеге я тоже не могу разобраться сейчас.
Я зависаю на моменте как по другому реализовать подсветку нажатой кнопки, не зная предыдущую нажатую, чтобы `снять `с неё подсветку.

2022-07-20 12:12 UTC, webgolub commented on js/filter.js
> +  switch (evt.target.id){
Допустим, код:
``` js
 evt.target.classList.add('img-filters__button--active');
        selectedFilterButton.classList.remove('img-filters__button--active');
        selectedFilterButton = evt.target;
```
Я могу вынести в функцию, но ты же не об этом пишешь? Тут и использование отдельной переменной для хранения элемента кнопки избыточно, как ты написал. Я правильно понимаю, что нужно полностью переписывать функцию `filterButtonClickHandler`?

2022-07-20 12:17 UTC, webgolub commented on js/filter.js
> +  return filteredPictures;
Проблема в том что функция возвращает нефильтрованный массив в одном из случаев или в том что возвращает не копию массива, а оригинал, который был ей передан?

2022-07-20 12:31 UTC, webgolub commented on js/util.js
> +    timeoutId = setTimeout(() => callback.apply(this, rest), timeoutDelay);
Эту функцию предоставляет «Кекс», я просто её скопировал как есть, не ожидая что с ней могут быть проблемы. Переписал на твой вариант, хотя контекст и замыкания пока что вызывают у меня сложности и я не особо понял смысл.

2022-07-20 12:48 UTC, webgolub commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
UPD: а зачем выносить в отдельный модуль функцию filterPictures? Можно ли не выносить?

2022-07-20 13:02 UTC, webgolub commented on js/picture.js
> +  }
А проверку перед удалением можно не делать, получается? Если картинки не отрисованы, будет ошибка же или нет?

2022-07-20 15:27 UTC, AlexMasterov commented on js/filter.js
> +  return filteredPictures;
> Проблема в том что возвращает не копию массива, а оригинал, который был ей передан?

Это.

2022-07-20 15:44 UTC, AlexMasterov commented on js/picture.js
> +  }
> А проверку перед удалением можно не делать, получается? Если картинки не отрисованы, будет ошибка же или нет?


См. [Document.`querySelectorAll`](https://developer.mozilla.org/ru/docs/Web/API/Document/querySelectorAll#%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B0%D0%B5%D0%BC%D0%BE%D0%B5_%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D0%B5):
> **Возвращаемое значение**

> <...> пустой `NodeList` в случае отсутствия совпадений

```js
[].forEach
```
Ошибки не будет.

2022-07-20 15:44 UTC, AlexMasterov commented on js/picture.js
> +  }
const removeElement = (element) `=>` element.remove();

Так функция явно возвращает значение.

> И можно ли записать эту функцию в одну строчку без {}?

Если бы метод `.remove` возвращал значение, например, удаленный элемент, то это бы негативно повлияло на компилируемый код движка. На текущем уровне можно о таком не думать.

2022-07-20 19:29 UTC, AlexMasterov approved these changes

2022-07-20 19:29 UTC, AlexMasterov commented on js/picture.js
> +  document.querySelectorAll('.picture').forEach(removeElement);
<details>
<summary>picture.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/picture.js#L11
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/picture.js#L46-L47
</details>

См. еще раз мой пример:

```diff
- document.querySelectorAll('.picture').forEach(removeElement);
+ picturesContainer.querySelectorAll('.picture').forEach(removeElement);
```

2022-07-20 19:29 UTC, AlexMasterov commented on js/picture.js
> +const deleteRenderedPictures = () => {
```diff
- const deleteRenderedPictures = () => {
+ const removePictures = () => {
```

2022-07-20 19:29 UTC, AlexMasterov commented on js/util.js
> +const debounce = (callback, timeoutDelay = DEBOUNCE_DEFAULT_TIMEOUT) => {
В этом случае константа выглядит несуразна.

```diff
- const debounce = (callback, timeoutDelay = DEBOUNCE_DEFAULT_TIMEOUT) => {
+ const debounce = (callback, timeoutDelay = 500) => {
```

const debounce = (callback, `timeoutDelay = 500`) => {

Так лучше, но некоторые без понимания могут придраться. Поэтому "на заметку".

2022-07-20 19:29 UTC, AlexMasterov commented on js/filter.js
> +const showFiltersSelector = () => {
```diff
- const showFiltersSelector = () => {
+ const showFilters = () => {
```
```diff
- const showFiltersSelector = () => {
+ const showFilterButtons = () => {
```

2022-07-20 19:29 UTC, AlexMasterov commented on js/filter.js
> +const Filter = {
`Filter` _чего_?

> Забыл, что в критерия неудачный пример

```diff
- const Filter = {
+ const FilterType = {
```

После этой доработки перечисление можно перенести в модуль с константами `const.js`, которые в том числе описывают фикс. значения из ТЗ. 

> Сейчас значения указывают на значения атрибута `id` разметки, т.е. мы подстраиваемся под разметку, а не оборот — в рамках этого интенсива некритично. Править разметку и создавать атрибуты `data-` не нужно

2022-07-20 19:29 UTC, AlexMasterov commented on js/filter.js
> +filtersSelector.addEventListener('click', filterButtonClickHandler);
`filtersSelector` + `click` !== `filterButton`ClickHandler

Д4

2022-07-20 19:30 UTC, AlexMasterov commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
> а зачем выносить в отдельный модуль функцию filterPictures?

Фильтрация данных не имеет прямого отношения к модулю, который управляет элементов с кнопками для фильтра.

> Можно ли не выносить?

Можно. 

> Похоже, что актуальные критерии позволяют написать весь проект в одном модуле 😃

2022-07-20 19:33 UTC, AlexMasterov commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
> Эту функция следует перенести в отдельный модуль и убрать из неё _неявный_ побочный эффект с удалением класса в DOM.

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L31

Нужно _вообще_ убрать из этой функции побочный эффект, чтобы функция стала _чистой_ и её можно было без проблем перенести в отдельный модуль.

Вместо этого следует получать название (тип) фильтра из параметра:

<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L28
</details>

```diff
- const filterPictures = (pictures) => {
+ const filterPictures = (pictures, filterType = FilterType.DEFAULT) => { 
```

2022-07-20 19:35 UTC, AlexMasterov commented on js/util.js
> +    timeoutId = setTimeout(() => callback.apply(this, rest), timeoutDelay);
У этой функции тяжелая история. Было еще хуже 😃

2022-07-20 19:41 UTC, AlexMasterov commented on js/filter.js
> +  return filteredPictures;
<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L29
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L33
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L37
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L41
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L46
</details>

> Проблема в том что функция возвращает нефильтрованный массив (несмотря на название) в одном из случаев

Например, [Array.p.`filter`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) всегда возвращает _новый_ массив, даже если ей передать пустой массив или коллбэк, которые ничего не фильтрует.

Твоя функция все еще может вернуть прежний массив, что нарушает ожидания по работе функций фильтрации, тем более с таким названием. Получив свой прежний массив, но не зная об этом, можно начать его небезопасно мутировать, что скажется на исходном массиве.

2022-07-20 19:45 UTC, AlexMasterov commented on js/filter.js
> +  return filteredPictures;
<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L29
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L33
</details>

В этой функции временная переменная `filteredPictures` уместна, если её сразу указать копию массива, т.е. результат `.slice`. Тогда далее его можно убрать и тем самым немного упростить и даже сократить код.

> Создание переменных и операции `=` имеют свою стоимость

Без подобных оснований её лучше упразднить и сразу возвращать результат фильтрации:

```js
case Filter.RANDOM:
  return pictures.slice().sort(() => 0.5 - Math.random()).slice(0, RANDOM_PICTURES_COUNT);

case Filter.DISCUSSED:
  return pictures.slice().sort((pictureA, pictureB) =>
    pictureB.comments.length - pictureA.comments.length
  );
```

2022-07-20 19:48 UTC, AlexMasterov commented on js/filter.js
> +  return filteredPictures;
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L32-L34

Это можно попробовать обосновать как заготовку на будущие.

Но лучше упразднить, а в качестве ветки `DEFAULT` использовать `default:` самого `switch` или `return` функции (после `switch`).

2022-07-20 19:54 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
<details>
<summary>filter.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L18-L26
</details>

<details>
<summary>Покажи пример получше</summary>

```js
// filter.js
const filterButtonClickHandler = (evt) => {
  const currentButton = evt.target;
  const activeButton = filtersSelector.querySelector('img-filters__button--active');

  if (currentButton !== activeButton) {
    activeButton.classList.remove('img-filters__button--active');
    currentButton.classList.add('img-filters__button--active');
  }

  filterChangeCallback(currentButton.id);
};
```
```js
// main.js
setFilterChangeHandler(
  debounce((filterType) => {
    deleteRenderedPictures();
    renderPictures(filterPictures(pictures, filterType));
  },
  )
);
```
</details>

См. также:
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/10#discussion_r925939307
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/10#discussion_r925982549
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/10#discussion_r925985197

2022-07-20 20:02 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
Для проверяющего лучше оставить повторную отрисовку по клику на кнопки фильтрации, чтобы можно было без переключения кнопок случайным образом сортировать изображения или отсортировать их по актуальным кол. комментариев.

> В каком случае, _где_ и _как_, следует проверять, что клик произошел по уже активной кнопки, нужно ли вызывать коллбэк и т.п. — вопросы архиважные, но их лучше оставить на другие интенсивы. Там еще будут подобные задачи

2022-07-20 20:05 UTC, AlexMasterov commented on js/main.js
> +getData((pictures) => {
<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/main.js#L8-L18
</details>

При открытии модуля `main.js`, который использует в роли "точки входа в приложение", уже можно увидеть и понять общею логику всего приложения. 

Жаль, только её _часть_. Например, за пониманием работы отправки формы придется погружаться в модули дальше 😃

2022-07-20 20:06 UTC, merged

2022-07-20 20:22 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
> Я догадался как можно упростить «подсвечивание» кликнутой кнопке

Похожий подход уже разбирался [в одном из прошлых PR](https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/8#discussion_r917576348).

2022-07-21 17:08 UTC, webgolub commented on js/filter.js
> +  switch (evt.target.id){
```js
if (!filtersSelector.classList.contains('img-filters--inactive')){ 
   filterChangeCallback(); 
 } 
```

Тут я проверяю что блок с кнопками фильтров показан, т.к. если не проверять, то при ошибке загрузки данных можно будет кликать по кнопкам и получать необработанные ошибки в консоль.  А повторные клики по кнопкам отрисовывают фильтрованные фото.

2022-07-21 18:53 UTC, webgolub commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
Вынес функцию, но теперь не пойму как можно передавать ей аргумент с выбранным фильтром. Если задавать прямо в модуле main.js во время её вызова, то непонятно как можно применить debounce. Я не могу понять как это реализовать, помоги, пожалуйста.

2022-07-21 19:21 UTC, webgolub commented on js/filter.js
> +const Filter = {
```js
const hashtagEndingRegExp = /[^-_=+;:,.]$/m;
const hashtagRegExp = /^#[a-zA-Zа-яА-ЯёЁ0-9]{0,}$/;
```
Относятся к константам? Нужно ли их писать в UPPER_SNAKE_CASE?

2022-07-21 19:37 UTC, AlexMasterov commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
См. внимательно пример: https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/10#discussion_r926001045.

В примере выбранный тик фильтра передается в коллбэк и его значение можно получить в `main.js`, после чего передать в качестве аргумента функции фильтрации (которая тоже опирается на перечисление типов фильтра).

> Очень важно от себя ничего не "улучшать"

2022-07-21 19:47 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/3e66171fcc509cfacdca08472804078f4ea8c1e1/js/filter.js#L49

Лучше добавить обработчик в момент вызова `showFiltersSelector`.

Проблема в том, что вызвать `showFiltersSelector` можно без установки коллбэка и тогда всё равно будет ошибка вызова коллбэка. Здесь нужно проверять, что коллбэк является функцией (или имеет значение отличное от `null`, что менее безопасно):

<details>
<summary>Пример</summary>

```js
if (typepf filterChangeCallback === 'function') {
  filterChangeCallback(currentButton.id);
}
```
Неявно и менее безопасно:
```js
if (filterChangeCallback !== null) { // if (filterChangeCallback) { ... }
  filterChangeCallback(currentButton.id);
}
```
Немного лучше, но короткий синтаксис недоступен на этом интенсиве:
```js
filterChangeCallback?.(currentButton.id);
```
</details>

2022-07-21 19:49 UTC, AlexMasterov commented on js/filter.js
> +const Filter = {
На _этом_ интенсиве и для проверяющего лучше оставить так.

На сам вопрос отвечал в замечание в PR задание с реализацией валидации.

2022-07-21 19:54 UTC, webgolub commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
Отбой, в debounce неправильно пробрасывались параметры коллбэка. Мне подсказали глянуть в функцию, я вернул её в изначальное состояние и всё заработало.

2022-07-21 20:02 UTC, AlexMasterov commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
Текущий вариант `debounce` рабочий. (нужно разбираться в другом)

Примеры, которые тебе показываю, прежде сам проверяю на твоем коде.

2022-07-21 20:04 UTC, AlexMasterov commented on js/filter.js
> +  filtersSelector.classList.remove('img-filters--inactive');
> Мне подсказали глянуть в функцию, я вернул её в изначальное состояние и всё заработало

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/42427811d715aac27eb13fb2aad5e6a6e684bdf7/js/util.js#L25

```diff
- timeoutId = setTimeout(callback, timeoutDelay, rest); 
+ timeoutId = setTimeout(callback, timeoutDelay, ...rest); 
```

2022-07-21 20:44 UTC, webgolub commented on js/filter.js
> +  switch (evt.target.id){
> Для проверяющего на защите лучше оставить повторную отрисовку по клику на кнопки фильтрации, чтобы можно было без переключения кнопок случайным образом сортировать изображения или отсортировать их по актуальным кол. комментариев.

Чтобы не добавлялся класс `'img-filters__button--active'`  контейнеру кнопок, я добавил && в условие
` if (currentButton !== selectedButton && currentButton !== filtersSelector)`
В случае, если `filterChangeCallback(currentButton.id)` вынесен из if, при клике на контейнер кнопок всё равно выполняется фильтрация по сценарию FilterType.DEFAULT один раз. Не могу понять причину такого поведения.

2022-07-21 20:46 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
См. https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/10#discussion_r926006852:

> Для проверяющего на защите лучше оставить повторную отрисовку по клику на кнопки фильтрации, чтобы можно было без переключения кнопок случайным образом сортировать изображения или отсортировать их по актуальным кол. комментариев

На _этом_ интенсиве и для проверяющего не нужно это исправлять, тем более так.

2022-07-21 20:48 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
```js
setFilterChangeHandler(
  debounce((filterType) => {
    if (filterType === FilterType.DEFAULT) {
      return;
    }

    deleteRenderedPictures();
    renderPictures(filterPictures(pictures, filterType));
  },
  )
);
```

2022-07-21 20:58 UTC, webgolub commented on js/filter.js
> +  switch (evt.target.id){
> На этом интенсиве и для проверяющего не нужно это исправлять, тем более так.
То есть оставляю возможность контейнеру добавить класс активной кнопки, я правильно понял?

2022-07-21 21:05 UTC, webgolub commented on js/main.js
> +getData((pictures) => {
Ох, боюсь что в попытках разгребсти модуль формы я завалю все возможные дедлайны. 😔

2022-07-21 21:07 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
Просто оставь, как в моем примере. В нем класс активной кнопки устанавливается только в его отсутствие.

Перерисовка нужна в первую очередь для фильтров случайных фото и актуальный комментариев (этот кейс не воспроизводится с игрушечным проектом, но тоже важен).

> Ну и непонятно почему при клике на контейнер вообще происходит перерисовка картинок в состояние как у FilterType.DEFAULT. Это разве не является ошибкой?

Это уже оптимизация, которую на интенсивах никто не ждет и не оценивает. 

> Сделать так можно, но правильная или просто хорошая реализация непосильная для студентов этого интенсива. Нужна база с модульностью и т.п. Иначе снова будет непонятно, почему так, почему здесь проверка, а не там и т.п.

2022-07-21 21:20 UTC, webgolub commented on js/filter.js
> +  switch (evt.target.id){
Я использую как раз код из твоего примера:
```js
const filterButtonClickHandler = (evt) => {
  const currentButton = evt.target;
  const activeButton = filtersSelector.querySelector('.img-filters__button--active');

  if (currentButton !== activeButton) {
    activeButton.classList.remove('img-filters__button--active');
    currentButton.classList.add('img-filters__button--active');
  }

  if (typeof filterChangeCallback === 'function') {
    filterChangeCallback(currentButton.id);
  }
};
```
Но клик по контейнеру кнопок ломает всё:
```
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at HTMLElement.filterButtonClickHandler
```
Я и не могу понять, так и оставить?

2022-07-21 21:35 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
Это потому что обработчик добавляет на контейнере, а не на сами кнопки.

<details>
<summary>Решение 1</summary>

```js
const filterButtonClickHandler = (evt) => {
  if (evt.target.nodeName !== 'BUTTON') {
    return;
  }
  
  // ...
};
```
</details>

<details>
<summary>Решение 2</summary>

```js
const filterButtons = document.querySelectorAll('.img-filters__form button');

const showFiltersSelector = () => {
  // ...

  filterButtons.forEach((filterButton) => {
    filterButton.addEventListener('click', filterButtonClickHandler);
  });
}
```
</details>

2022-07-21 21:37 UTC, webgolub commented on js/filter.js
> +  switch (evt.target.id){
Я тоже подумал про добаление обработчика на каждую кнопку, спасибо.

2022-07-21 22:05 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
> Ну и непонятно почему при клике на контейнер вообще происходит перерисовка картинок в состояние как у FilterType.DEFAULT. Это разве не является ошибкой?

<details>
<summary>Пример</summary>

```js
// filter.js
const filterButtonClickHandler = (evt) => {
  // ...

  filterChangeCallback(currentButton.id, activeButton.id);
};
```

```js
// main.js
setFilterChangeHandler((currentFilter, previousFilter) => {
  if (currentFilter === FilterType.DEFAULT && currentFilter === previousFilter) {
    return;
  }

  debounce(() => {
    deleteRenderedPictures();
    renderPictures(filterPictures(pictures, currentFilter));
  });
})
```
</details>

2022-07-22 06:59 UTC, webgolub commented on js/filter.js
> +  switch (evt.target.id){
Спасибо за ответ. После того, как убрал делегирование с обработчика кликов по кнопкам, клики по контейнеру перестали вызывать какие-либо действия, даже без конструкции:
```js
if (FilterType === FilterType.DEFAULT){
        return;
}
```
Так что я эту конструкцию убрал.

2022-07-22 07:10 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
> После того, как убрал делегирование с обработчика кликов по кнопкам, клики по контейнеру перестали вызывать какие-либо действия

Не очень понял, но эта конструкция не причем. Надеюсь, что ты смог повесить обработчик на сами кнопки или добавить проверку на кнопку с делегированием, когда обработчик на контейнере.

> Эта конструкция недоработана (доработанная выше), и она была продолжение оптимизации, причем по твоему запросу 😃

2022-07-22 10:06 UTC, webgolub commented on js/filter.js
> +  switch (evt.target.id){
Я неверно выразился. После того как повесил обработчик на каждую кнопку отдельно, вместо делегирования, проблемы с кликом на контейнер ожидаемо не стало. И я удалил эту конструкцию из main.js:
```js
if (FilterType === FilterType.DEFAULT){
        return;
}
```

2022-07-22 10:19 UTC, AlexMasterov commented on js/filter.js
> +  switch (evt.target.id){
> Тогда её стоит вернуть т.к. это получается оптимизация

Она не будет правильно работать. Для оптимизации следует использовать более поздний пример: https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/10#discussion_r927138502.