Отрисуй меня полностью (часть 2)
htmlacademy-javascript/2049181-kekstagram-26 pull request #6
Opened 2022-06-29 08:51 UTC by webgolub

---
:mortar_board: [Отрисуй меня полностью (часть 2)](https://up.htmlacademy.ru/javascript/26/user/2049181/tasks/13)

:boom: https://htmlacademy-javascript.github.io/2049181-kekstagram-26/6/

2022-06-29 23:30 UTC, AlexMasterov requested changes

2022-06-29 23:30 UTC, AlexMasterov commented on js/render-thumbnails.js
> +const renderThumbnails = (thumbnails) => {
const render`Thumbnails` = (`thumbnails`) => {

См. ТЗ:
> Пользователям предоставлена возможность загружать свои **фотографии** или просматривать фотографии, загруженные ранее другими пользователями

По ТЗ основной сущностью в проекте являются фотографии (`photos`), данные о которых мы храним в базовых объектах. Один и тот же объект с данными фото может быть "отрисован" в элементе миниатюры и попапе в большом изображении.

```diff
- const renderThumbnails = (thumbnails) => {
+ const renderThumbnails = (photos) => {
```

2022-06-29 23:30 UTC, AlexMasterov commented on js/render-thumbnails.js
> +    const thumbnailClickHandler = renderFullsizeViewer({url, comments, likes, description});
<details>
<summary>renderFullsizeViewer</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L40-L53
</details>

К сожалению, у функции снова неудачное название.

Советую разделить на две функции: `renderFullsizeViewer` и обработчик событий DOM `thumbnailClickHandler`:

```js
element.addEventListener('click', (evt) => {
  evt.preventDefault();

  renderFullsizeViewer(thumbnail);
});
```

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +  if (evt.keyCode === 27){
if (evt.`keyCode` === 27){

См. [KeyboardEvent.`keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode):
> **Deprecated**: This feature is no longer recommended

Свойство `.keyCode` уже очень давно считается устаревшим и не рекомендовано к использованию. Используй альтернативы: `.code`, `.key` и т.п.

[`Д 8`](https://up.htmlacademy.ru/javascript/26/criteries#d8)
> API встроенных функций и объектов используется правильно

<details>
<summary>+ учесть на будущие</summary>

if (evt.keyCode === `27`){

[`Д 19`](https://up.htmlacademy.ru/javascript/26/criteries#d19)
> В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа
</details>

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +    // eslint-disable-next-line no-use-before-define
Предупреждаю, что линтер на защите игнорирует подобные директивы.

> Подобный код - маркер неудачного [разделения ответственности](https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D0%B8) и, как следствие, потери _модульности_

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +
<details>
<summary>viewer.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L9
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L12
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L19
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L21
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L43-L47
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L49-L51
</details>

<details>
<summary>viewer.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L31-L32
</details>

[`Д 21`](https://up.htmlacademy.ru/javascript/26/criteries#d21)
> Поиск элементов по селекторам делается минимальное количество раз, после этого **ссылки на элементы сохраняются [в переменные вне функций]**

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +const renderComments = (items) => {
const render`Comments` = (`items`) => {

🤔

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +  commentsContainer.textContent = '';
🤔

```diff
- commentsContainer.textContent = '';
+ commentsContainer.innerHTML = '';
```

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +    comment.querySelector('.social__text').textContent = items[i].message;
comment.querySelector('img').src = `items[i]`.avatar;
comment.querySelector('img').alt = `items[i]`.name;
comment.querySelector('.social__text').textContent = `items[i]`.message;

**3x** `items[i]`

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +  const elementsArray = [];
const element`sArray` = [];

Масло масленное.

[`Б 5`](https://up.htmlacademy.ru/javascript/26/criteries#b5)
> Массивы названы существительными во множественном числе

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +    commentsContainer.append(...elementsArray);
Добавить таким образом в контейнер следует только один раз _после цикла_.

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +  overlay.classList.remove('hidden');
Сейчас сначала показывается элемент попапа, а только потом происходит его изменение.

[`Б 25`](https://up.htmlacademy.ru/javascript/26/criteries#b25)
> Множественные DOM-операции производятся на элементах, которые не добавлены в DOM

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +    document.removeEventListener ('keydown', closeBigPictureEscHandler);
document.removeEventListener ('keydown', `close`BigPictureEscHandler);

> Название функции, которая используется в роли обработчика событий DOM, не должно начинаться с глагола - подобное по Б6 требуется только для обычных функций, которые вызываются в коде

[`Д 4`](https://up.htmlacademy.ru/javascript/26/criteries#d4)
> Название обработчика строится следующим образом:

> **(на каком элементе)** + **что случилось** + `Handler`

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +  overlay.querySelector('#picture-cancel').addEventListener('click', closeBigPictureClickHandler);
overlay.querySelector('#picture-cancel').addEventListener('click', `close`BigPictureClickHandler);


[`Д 4`](https://up.htmlacademy.ru/javascript/26/criteries#d4)
> Название обработчика строится следующим образом:

> **(на каком элементе)** + **что случилось** + `Handler`

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +  overlay.querySelector('#picture-cancel').addEventListener('click', closeBigPictureClickHandler);
overlay.querySelector('#picture-cancel').addEventListener('click', `close`BigPictureClickHandler)

[`Д 4`](https://up.htmlacademy.ru/javascript/26/criteries#d4)
> Название обработчика строится следующим образом:

> **(на каком элементе)** + **что случилось** + `Handler`

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +  document.addEventListener('keydown', closeBigPictureEscHandler);
document.addEventListener('keydown', `close`BigPictureEscHandler);

[`Д 4`](https://up.htmlacademy.ru/javascript/26/criteries#d4)
> Название обработчика строится следующим образом:

> **(на каком элементе)** + **что случилось** + `Handler`

2022-06-29 23:30 UTC, AlexMasterov commented on js/viewer.js
> +  document.addEventListener('keydown', closeBigPictureEscHandler);
<details>
<summary>viewer.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L12
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L21
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/67f43cff91344d0f1ebb9eb01e113c1c4b67973e/js/viewer.js#L43
</details>

и т.п.

_Добавление_ обработчиков дублируется.

[`Д 14`](https://up.htmlacademy.ru/javascript/26/criteries#d14)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2022-06-30 01:10 UTC, AlexMasterov commented on js/render-thumbnails.js
> +  thumbnailsContainer.append(...thumbnailElements);
👍🏻

2022-06-30 08:41 UTC, webgolub commented on js/viewer.js
> +  commentsContainer.textContent = '';
Я догадываюсь что есть на то причины, не мог бы пояснить почему для очистки содержимого тега нужен именно  `.innerHTML`, хотя `.textContent` тоже очистил содержимое тега в данном случае, присвоив ему значение?

2022-06-30 11:42 UTC, AlexMasterov commented on js/viewer.js
> +  commentsContainer.textContent = '';
`.textContent` "очищает" строку от разметки HTML, а в случае пустой строки этого не требуется.

2022-06-30 13:44 UTC, webgolub commented on js/render-thumbnails.js
> +    const thumbnailClickHandler = renderFullsizeViewer({url, comments, likes, description});
Тут просто до меня не доходит что нужно сделать. Сижу уже несколько часов и не могу понять.
Название `renderFullsizeViewer` неудачное или `renderThumbnails`?
```js
element.addEventListener('click', (evt) => {
  evt.preventDefault();

  renderFullsizeViewer(thumbnail);
});
```
А как я могу использовать `element.addEventListener()` снаружи функции, если разделю, ведь `element` объявлена внутри `renderThumbnails()`?
Прости за глупые вопросы, но я правда не могу разобраться, просто в ступоре.

2022-06-30 19:09 UTC, AlexMasterov commented on js/render-thumbnails.js
> +    const thumbnailClickHandler = renderFullsizeViewer({url, comments, likes, description});
> Название renderFullsizeViewer неудачное или renderThumbnails?

См. название спойлера 😃

Функция с названием `renderFullsizeViewer` вместо рендера создает обработчик события DOM, что, например меня, вводит в заблуждение. 

В созданном обработчике событий смешена работа с объектом событием и логика показа (рендера) попапа. Поэтому, как _первый_ шаг, предложил это разделить, например, так:

<details>
<summary>Пример</summary>

```js
// create-thumbnail.js
const createThumbnail = (photo) => {
  const element = thumbnailTemplate.cloneNode(true);

  element.querySelector('img').src = url;
  element.querySelector('.picture__comments').textContent = comments.length;
  element.querySelector('.picture__likes').textContent = likes;

  return element;
};

const renderThumbnail = (photo) => {
  const { url, comments, likes } = photo;

  const element = createThumbnail(photo);
  element.addEventListener('click', (evt) => {
    evt.preventDefault();

    renderFullsizeViewer(photo);
  });

  return element;
};

const renderThumbnails = (photos) => {
  thumbnailsContainer.append(...photos.map(renderThumbnail));
};
```
</details>

> А как я могу использовать `element.addEventListener()` снаружи функции, если разделю, ведь `element` объявлена внутри `renderThumbnails()`?

Пожалуйста, посмотри пример и уточни, что значит "снаружи функции" 😃

2022-07-01 11:46 UTC, AlexMasterov commented on js/render-modal.js
> +const bodyNode = document.querySelector('body');
В поиске `body` по через `querySelector` и самой переменной `bodyNode` мало смысла: элемент `body` доступен через свойство `document.body`.

2022-07-01 11:46 UTC, AlexMasterov commented on js/render-modal.js
> +
const modal`Node` = document.querySelector('.big-picture');
и т.п.

<details>
<summary>create-thumbnail.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7ae6db87f601c4480f246b1a14da52206dd559e8/js/create-thumbnail.js#L2
</details>

<details>
<summary>render-thumbnails.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/5a805afdfd0459cef411f930374c9cb80b6563b9/js/render-thumbnails.js#L4
</details>

<details>
<summary>render-modal.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7ae6db87f601c4480f246b1a14da52206dd559e8/js/render-modal.js#L20
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7ae6db87f601c4480f246b1a14da52206dd559e8/js/render-modal.js#L22
</details>

и т.п.

Все эти переменные также указывают на DOM-элементы (= объекты типа `Element`), но в их названии не используется суффикс `Node`, что нарушает критерий по _единообразию_ в именовании.

Если для названий переменных с DOM-элементами **решил** использовать суффикс `Node`, то его следует использовать для всех подобных переменных _во всем проекте_ (и внимательно следить за этим). Или не использовать, то тогда суффикс `Node` нужно убрать.

[`Д 6`](https://up.htmlacademy.ru/javascript/26/criteries#d6)
> Используется единый стиль именования переменных

> если переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element), содержат слово `Element` **или любое другое, но одно и то же везде**

**JS2**-Д6
> если есть переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element) и содержат слово `Element`, **то это правило работает везде**

2022-07-01 11:46 UTC, AlexMasterov commented on js/render-modal.js
> +    const item = comments[i];
Сейчас в цикле `for` значение инкремента `i` используется только для получения элемента из массива, без доп. логики.

Нужно переписать `for` на `for of` или `.forEach` / `.map`

> На защите проекта могут придраться

[`Д 26`](https://up.htmlacademy.ru/javascript/26/criteries#d26)
> Для работы с JS-коллекциями используются итераторы для массивов

2022-07-01 11:46 UTC, AlexMasterov commented on js/render-modal.js
> +
<details>
<summary>render-modal.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7ae6db87f601c4480f246b1a14da52206dd559e8/js/render-modal.js#L69
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/7ae6db87f601c4480f246b1a14da52206dd559e8/js/render-modal.js#L81
</details>

`function`

> `openPictureModal` можно сделать стрелочной функцией

> [Повторю](https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/6#discussion_r910455372), что это _костыль_, а не решение проблемы с неудачным распределением ответственности: добавлять обработчик  `keydown` на `document` следует в модуле уровня выше, который работает с `.pictures` и связывает миниатюру с попапом

[`Д 5`](https://up.htmlacademy.ru/javascript/26/criteries#d5)
>  Все функции объявлены единообразно

> При объявлении функций используются _стрелочные_ функции

2022-07-01 11:46 UTC, AlexMasterov commented on js/render-modal.js
> +export {openPictureModal, closePictureModal};
export {openPictureModal, `closePictureModal`};

Функция `closePictureModal` экспортируется, но в других модулях не используется. Тогда нужно удалить из экспорта.

> Напомню, что [в моем примере](https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/6#discussion_r911366408) попап только предоставляет возможность с помощью коллбэка узнать о клике по кнопке, а реагирует на это закрытием попапа (`closePictureModal`) модуль уровнем выше, который работает с  `.pictures` 

> Добавлять и удалять обработчик `keydown` на `document` желательно тоже на уровне выше,  в модуле, который работает с `.pictures` и тем самым находится ближе к корню всего документа. Тогда проблемы с костылем `function` быть не может, поскольку - это следствие неудачного распределение ответственности между модулями. Проблема не там, где боль

2022-07-01 11:51 UTC, AlexMasterov commented on js/render-modal.js
> +  modalCommentsContainerNode.replaceChildren();
modalCommentsContainerNode.`replaceChildren()`;

👍🏻

2022-07-01 11:53 UTC, AlexMasterov commented on js/render-modal.js
> +  bodyNode.classList.add('modal-open');
Порядок вызова 👍🏻

2022-07-01 11:53 UTC, merged

2022-07-01 12:07 UTC, AlexMasterov commented on js/util.js
> +const isEscKey = (evt) => evt.key === 'Escape';
См. [MDN](https://developer.mozilla.org/ru/docs/Web/API/UI_Events/Keyboard_event_key_values#:~:text=%D0%92%20Internet%20Explorer%20(%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%B5%D0%BD%D0%BE%20%D0%B2%20%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F%D1%85%209%20%D0%B8%2011)%20%D0%B8%20Firefox%2036%20%D0%B8%20%D0%B1%D0%BE%D0%BB%D0%B5%D0%B5%20%D1%80%D0%B0%D0%BD%D0%BD%D0%B8%D1%85):
> В Internet Explorer (проверено в версиях 9 и 11) и Firefox 36 и более ранних, клавиша Esc возвращает значение "Esc" вместо "Escape"

2022-07-01 18:21 UTC, webgolub commented on js/render-modal.js
> +
Подскажи, в реальной жизни постфиксы эти насколько часто используются? Из твоего опыта — лучше юзать их или можно не?

2022-07-01 18:53 UTC, AlexMasterov commented on js/render-modal.js
> +
Прежде всего, см. [В чём разница между узлом и элементом DOM?](https://habr.com/ru/company/ruvds/blog/539096/).

В проектах на чистом JS суффиксы используются как `type/role hint` себе и другим. В случае DOM чаще видел `Element`, чем `Node`. В проектах на TS чаще опираются на типы и вообще опускают суффиксы.

На всех интенсивах по JS в основном будем работать с узлами типа `Element` и многие утилитарные функции будут явно на это завязаны. Поэтому здесь мне ближе `Element`, но можно использовать `Node` как его обобщение.

Отслеживать, что значение переменный указывает на DOM-элемент (= `instanceof Element`) может превратиться в Сизифов труд. Обычно про суффикс забывают в названиях параметрах функций, в том числе сами авторы курса. Если у тебя есть свободное время и желание, то на этом интенсиве попробуй его использовать 😃

2022-07-01 19:04 UTC, webgolub commented on js/render-modal.js
> +    const item = comments[i];
Честно подглядел в дискорде вариант с выносом в функцию создания одного коммента и обработки ею массива комментариев уже в функции рендера модального окна. Там как раз .map, но с replaceChildren.

2022-07-01 19:13 UTC, webgolub commented on js/render-modal.js
> +  bodyNode.classList.add('modal-open');
Честно говоря, не помню чем руководствовался когда написал. А сейчас задался вопросом, а чем хуже  будет сначала добавить класс на `<body>`, а потом уже удалить  `.hidden` у попапа?

2022-07-01 19:28 UTC, AlexMasterov commented on js/render-modal.js
> +  bodyNode.classList.add('modal-open');
> чем хуже будет сначала добавить класс на <body>, а потом уже удалить .hidden у попапа?

Элемент попапа станет видимым и тем самым **включиться в рендеринг браузера**. Тогда некоторые изменения видимого элемента могут вызывать принудительную _перерисовку_ и _пересчет_ стилей (layout / reflow). Это может нарушить оптимальный цикл рендеринга. Кроме этого, почти все эти операции выполняются _синхронно_, т.е. с блокировкой выполнения JS и всей страницы. 

См. [What forces layout / reflow](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).

2022-07-01 20:43 UTC, webgolub commented on js/render-modal.js
> +  bodyNode.classList.add('modal-open');
Извини, я неверно понял контекст комментария: почему-то я подумал что речь про порядок вызова в строках
``` js
modalNode.classList.remove('hidden');
bodyNode.classList.add('modal-open');
```
То, почему эти две строки
``` js
renderModalNode(photo);
modalNode.classList.remove('hidden');
```
 именно в таком порядке, я понял из твоего прошлого [комментария](https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/6#discussion_r910483200), спасибо.

2022-07-01 21:54 UTC, webgolub commented on js/render-modal.js
> +
Очень сложно с пониманием принципов проектирования ПО на данном этапе. Я просто не могу уложить это в голове, спасибо что указываешь на эти ошибки. Сорян, что не улавливаю многие твои советы, ибо пока очень сложно перестроить своё мышление. 

Сейчас я вынес оба обработчика в модуль, который связывает миниатюру с попаом, хоть ты и написал только про обрботчик `keydown `на `document`, но иначе у меня возникала та же проблема использования функции`closePictureModal()` в обработчике клика по кнопке закрытия попапа, до её объявления. Толком пока не разобрался куда и почему нужно выносить определённые функции, если честно. Из-за каши в голове даже вопрос правильно сформулировать пока что не могу.

Когда ранее добавлял обработчики в модуль попапа, я предполагал что обработчики - это часть логики работы отрисовщика попапа. Сейчас догадываюсь что неправильно сваливать всё в одну кучу, гуглю про разделение ответственности, читаю.

2022-07-01 22:08 UTC, AlexMasterov commented on js/render-modal.js
> +
> Сейчас я вынес оба обработчика в модуль, который связывает миниатюру с попаом, хоть ты и написал только про обрботчик keydown на document, но иначе у меня возникала та же проблема использования функцииclosePictureModal() в обработчике клика по кнопке закрытия попапа, до её объявления

<details>
<summary>Покажи пример</summary>

```js
// render-thumbnails.js - желательно переименовать в сущ.
import {
  openPictureModal,
  closePictureModal,
  setPictureModalCloseButtonClickHandler,
};

const onEscKeydown = (evt) => {
  closePictureModal();
  document.removeEventListener('keydown', onEscKeydown);
};

const renderThumbnail = (photo) => {
  const node = createThumbnail(photo);

  node.addEventListener('click', (evt) => {
    evt.preventDefault();

    openPictureModal(photo);
    setPictureModalCloseButtonClickHandler(() => {
      closePictureModal();
      document.removeEventListener('keydown', onEscKeydown);
    })

    document.addEventListener('keydown', onEscKeydown);
  });

  return node;
};
```
</details>

2022-07-02 07:52 UTC, webgolub commented on js/render-modal.js
> +
>// render-thumbnails.js - желательно переименовать в сущ.

Я правильно понял, что нужно переименовать в существительное - например `thumbnails` или `gallery`?

>Покажи пример

Прости мою непонятливость, но заголовок спойлера как будто просит меня показать свой пример, как я сделал, а внутри ты показываешь свой пример. Как воспринимать заголовок?

> В примере выше логику нажатия кнопки с крестиком определяет модуль уровня выше...

Опять же голова кипит, и я многое упускаю, но в коде под спойлером вижу только работу с обработчиком события `keydown`, но не `click` по кнопке с крестиком. Вот что я сделал на данный момент:

```js
// Модуль render-thumbnails.js
import {createThumbnail} from './create-thumbnail.js';
import {openPictureModal, closePictureModal} from './render-modal.js';
import {isEscKey} from './util.js';

// Контейнер для миниатюр
const thumbnailsContainer = document.querySelector('.pictures');
// Кнопка закрытия модального окна
const modalCloseButton = document.querySelector('.big-picture').querySelector('#picture-cancel');

// Обработчик нажатия на клавишу ESC
const onModalEscKeydown = (evt) => {
  if (isEscKey(evt)){
    evt.preventDefault();
    closePictureModal();
  }
};

// Обработчик клика по кнопке закрытия модального окна
const onModalCloseButtonClick = (evt) => {
  evt.preventDefault();
  closePictureModal();
};


const renderThumbnail = (photo) => {
  const thumbnail = createThumbnail(photo);

  thumbnail.addEventListener('click', (evt) => {
    evt.preventDefault();
    
    openPictureModal(photo);
    modalCloseButton.addEventListener('click', onModalCloseButtonClick);
    document.addEventListener('keydown', onModalEscKeydown);
  });

  return thumbnail;
};

const renderThumbnails = (photos) => {
  thumbnailsContainer.append(...photos.map(renderThumbnail));
};

export {renderThumbnails, onModalCloseButtonClick, onModalEscKeydown};
```

```js
// Модуль render-modal.js
import {onModalEscKeydown, onModalCloseButtonClick} from './render-thumbnails.js';

// Модальное окно просмотра большого изображения
const modalWindow = document.querySelector('.big-picture');
// Контейнер для комментариев в модальном окне
const modalCommentsContainer = modalWindow.querySelector('.social__comments');
// Шаблон комментария в модальном окне
const modalCommentTemplate = modalCommentsContainer.querySelector(':first-child');

// Большое изображение в модальном окне
const modalBigPicture = modalWindow.querySelector('.big-picture__img').querySelector('img');
// Счётчик лайков в модальном окне
const modalLikesCount = modalWindow.querySelector('.likes-count');
// Счётчик комментариев в модальном окне
const modalCommentsCount = modalWindow.querySelector('.comments-count');
// Подпись к большому изображению
const modalSocialCaption = modalWindow.querySelector('.social__caption');
// Количество отображённых комментариев
const modalSocialCommentsCount = modalWindow.querySelector('.social__comment-count');
// Кнопка загрузки новой порции комментариев
const modalCommentsLoaderButton = modalWindow.querySelector('.comments-loader');
// Кнопка закрытия модального окна
const modalCloseButton = modalWindow.querySelector('#picture-cancel');

// Функция создания DOM-узла комментария
const createComment = (comment) => {
  const newComment = modalCommentTemplate.cloneNode(true);
  const commentImage = newComment.querySelector('img');
  commentImage.src = comment.avatar;
  commentImage.alt = comment.name;
  newComment.querySelector('.social__text').textContent = comment.message;

  return newComment;
};

// Функция рендера модального окна просмотра полноразмерного изображения
const renderModalWindow = ({url, likes, comments, description}) => {
  modalBigPicture.src = url;
  modalLikesCount.textContent = likes;
  modalCommentsCount.textContent = comments.length;
  modalSocialCaption.textContent = description;
  modalCommentsContainer.replaceChildren(...comments.map(createComment));
  modalSocialCommentsCount.classList.add('hidden');
  modalCommentsLoaderButton.classList.add('hidden');
};

// Функция открытия модального окна
const openPictureModal = (photo) => {
  // 1. Показать окно
  renderModalWindow(photo);
  modalWindow.classList.remove('hidden');
  document.body.classList.add('modal-open');
};

// Функция закрытия модального окна
const closePictureModal = () => {
  // 1. Скрыть окно
  modalWindow.classList.add('hidden');
  document.body.classList.remove('modal-open');
  // 2. Удалить обработчики для закрытия
  modalCloseButton.removeEventListener('click', onModalCloseButtonClick);
  document.removeEventListener('keydown', onModalEscKeydown);
};

export {openPictureModal, closePictureModal};

```

2022-07-02 08:05 UTC, AlexMasterov commented on js/render-modal.js
> +
Оставь, как есть 😃