Module9 task1
htmlacademy-javascript/2049181-kekstagram-26 pull request #8
Opened 2022-07-09 22:15 UTC by webgolub

2022-07-10 00:52 UTC, AlexMasterov requested changes

2022-07-10 00:52 UTC, AlexMasterov commented on js/editor-scale.js
> +  scaleValueDisplay.value = '100%';
scaleValueDisplay.value = `'100%'`;

На защите проекта _могут_ придраться.

[`Б 7`](https://up.htmlacademy.ru/javascript/26/criteries#b7)
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2022-07-10 00:52 UTC, AlexMasterov commented on js/editor-scale.js
> +  scaleValueDisplay.value = '100%';
> Рендер поля делается _в обход_ своей функции `renderScale` 🤔

> При подобном _изменении поля_ слушатель (`editor-scale.js`) коллбэка `setScaleChangeHandler` о нем не узнает, что нарушает _идею_ инкапсуляции (= интерфейс функции "обманывает" и заставляет изучать исходники)

<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/178126737-b993da05-e543-4f17-a25e-ee885617bef5.png)

</details>

Если открыть форму загрузки фотографии и изменить масштаб, то после повторного открытия формы фотография остается масштабированной.

См. ТЗ 3.6:
> Нажатие на кнопку `#upload-cancel` приводит к [закрытию формы](https://up.htmlacademy.ru/javascript/26/project/kekstagram#kekstagram-1-3) и возвращению всех данных и контрола фильтра к исходному состоянию (описано в [пункте 3.3](https://up.htmlacademy.ru/javascript/26/project/kekstagram#kekstagram-3-3))

2022-07-10 00:52 UTC, AlexMasterov commented on js/editor-effects.js
> +
<details>
<summary>editor-effects.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L12
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L136
</details>

<details>
<summary>editor-effects.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L30
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L34
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L38
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L43
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L48
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L52
</details>

<details>
<summary>editor-effects.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L70
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L74-L75
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L87
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L99
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L111
</details>

> Строковые значения эффектов описаны в ТЗ, а здесь используются, многократно

На защите проекта _могут_ придраться. Например, попросить создать организовать эти строки в _перечисление_.

[`Б 7`](https://up.htmlacademy.ru/javascript/26/criteries#b7)
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2022-07-10 00:52 UTC, AlexMasterov commented on js/editor-effects.js
> +effectsRadioContainer.addEventListener('change', (evt) => renderEffect(evt));
<details>
<summary>editor-effects.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L150
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L142-L146
</details>

Реализация таким образом обработчика и передача объекта события `evt` далее в обычные функции — неудачное решение, которое может привести к проблемам.

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L69

Вместо всего объекта события `evt`, которые передается _ссылочным_ образом (!), лучше сразу передать значение `.value` (название эффекта), которое только и требуется функции для работы.

2022-07-10 00:52 UTC, AlexMasterov commented on js/editor-effects.js
> +
<details>
<summary>editor-effects.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L76-L84
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L88-L96
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L100-L108
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L112-L120
</details>

На защите проекта _могут_ придраться.

[`Д 14`](https://up.htmlacademy.ru/javascript/26/criteries#d14)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2022-07-10 00:52 UTC, AlexMasterov commented on js/editor-effects.js
> +      units = 'px';
В таком решение использование временной переменной `units ` (с операцией переприсвоения) выглядит избыточным.

2022-07-10 00:52 UTC, AlexMasterov commented on js/editor-effects.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/178127111-889e1137-6943-45c0-b8e6-5573fac5aa1f.png)
</details>

При повторном открытии формы загрузки фотографии мощность ползунка эффекта не сбрасывается.

Нужно разобраться и исправить.

2022-07-10 00:52 UTC, AlexMasterov commented on js/editor-effects.js
> +sliderContainer.noUiSlider.on('update', () => {
Добавление обработчика находится между определений функций, что усложняет чтение.

> На JS2 будет критерий с запретом подобного, но _привычки_ уже могут быть сформированы

2022-07-10 01:52 UTC, AlexMasterov commented on js/editor-effects.js
> +  imgPreview.className = '';
Таким образом будут удалены _все_ классы у элемента, а не только `effects__preview--`.

2022-07-10 01:55 UTC, AlexMasterov commented on js/editor-effects.js
> +const imgPreview = uploadForm.querySelector('.img-upload__preview img');
Еще раз обращу внимание, что работать с этим элементом следует в `editor.js`.

2022-07-10 02:06 UTC, AlexMasterov commented on js/editor-effects.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/178128463-a67d7d5d-ead0-46a7-8b33-84b20c087cfe.png)

</details>

При открытии формы загрузки фотографии при выборе (по умолчанию) отсутствии эффекта показывает ползунок для его регулирование.

См. ТЗ:
> При выборе эффекта «Оригинал» слайдер скрывается

2022-07-10 02:08 UTC, AlexMasterov commented on js/editor-effects.js
> +const imgPreview = uploadForm.querySelector('.img-upload__preview img');
_На будущие_ снова обращаю, что работать с элементом `imgPreview` следовало в модуле `editor.js`.

2022-07-10 08:27 UTC, webgolub commented on js/editor-scale.js
> +  scaleValueDisplay.value = '100%';
>слушатель (`editor-scale.js`) коллбэка `setScaleChangeHandler`

Общая мысль о том что значение поля меняется явно, а не через функцию `renderScale` мне понятна.
Но не могу идентифицировать кто есть этот слушатель - это же слушатель событий в который передан коллбэк `setScaleChangeHandler`? То есть это `addEventListener('click',` в который передана `resetScale`, которая уже вызывает `setChangeCallback`?

2022-07-10 09:13 UTC, webgolub commented on js/editor-effects.js
> +
Если в данный момент ползунок скрыт при выборе «оригинал» (при открытии формы)  — можно ли в таком случае считать сброс ползунка не нужным? В ТЗ вроде нет такого требования.

2022-07-10 10:00 UTC, AlexMasterov commented on js/editor-effects.js
> +
> Если в данный момент ползунок скрыт при выборе «оригинал» (при открытии формы) — можно ли в таком случае считать сброс ползунка не нужным?

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/6a88cec4687fd3dc91b839cbfd61280c4c43edde/js/editor-effects.js#L61

В этом случае форма отправится с неверными данными.

> В ТЗ вроде нет такого требования

В другом замечание [процитировал ТЗ](https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/8#discussion_r917321935), где в случае _отправки_ и _закрытия_ формы явно требуется:

> все данные, введённые в форму, и **контрол фильтра** приходят в исходное состояние

2022-07-10 10:08 UTC, webgolub commented on js/editor-effects.js
> +  imgPreview.className = '';
Я убрал ненужное удаление классов внутри `addEffectToImgPreview`, т.к. они уже удаляются в вышестоящей функции `resetEffects`

2022-07-10 10:16 UTC, webgolub commented on js/editor-effects.js
> +const imgPreview = uploadForm.querySelector('.img-upload__preview img');
Понял, спасибо что отметил. Для меня пока что сложно вынести во внешний модуль реализацию добавления классов и стилей к `imgPreview` . Я думал над этим, но потом решил не тратить время, которого и так немного.

2022-07-10 10:22 UTC, AlexMasterov commented on js/editor-effects.js
> +  imgPreview.className = '';
> или это плохая практика (критерий [26?](https://up.htmlacademy.ru/profession/react/10/javascript/26/criteries#d23) )

1. Да, практика плохая;
2. Да, _могут_ справедливо придраться по критерию Б26 — это зависит от уровня проверяющего и его мотивации, а также отчасти от уровня твоего кода 😃

2022-07-10 10:28 UTC, AlexMasterov commented on js/editor-effects.js
> +const imgPreview = uploadForm.querySelector('.img-upload__preview img');
> Я думал над этим, но потом решил не тратить время, которого и так немного

 Проблема в том, что начинающие выбирают, как им кажется, легкий путь, который обычно сильно _усложняет_ проект, а это негативно влияет на [стоимость будущих изменений](https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D1%85%D0%BD%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B4%D0%BE%D0%BB%D0%B3). Подвох в том, что модульность ускоряет реализацию ТЗ и позволяет отправлять задания параллельно, без рисков конфликта Гита.

2022-07-10 10:55 UTC, webgolub commented on js/editor-effects.js
> +const imgPreview = uploadForm.querySelector('.img-upload__preview img');
Я хочу научиться делать правильно, только боюсь не успеть сдать проект. Специально «лёгкий путь» не выбираю, ибо понял что легко не будет при любых раскладах 😃

Помоги, пожалуйста, нащупать верный путь. Сейчас я думаю что нужно  `renderEffectIntensity`, `resetEffects` и `addEffectToImgPreview` импортировать в `editor.js`, т.к. в них я работаю с imgPreview. Так же мне скорее всего нужно будет знать `currentEffect`, так что и её нужно импортировать.

Я не могу сложить в голове чёткую структуру программы: какой модуль что делает и почему. Начинаю думать об одном - другое из головы вываливается, сложно научиться мыслить алгоритмами, если месяц назад об этом даже не задумывался.

2022-07-10 13:00 UTC, AlexMasterov approved these changes

2022-07-10 13:00 UTC, AlexMasterov commented on js/editor-effects.js
> +const Effects = {
const Effect`s` = {

> Перечисления названы существительными в _единственном_ числе

2022-07-10 13:00 UTC, AlexMasterov commented on js/editor-effects.js
> +      imgPreview.style.filter = `grayscale(${effectLevelValue.value})`;
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/efc15d854daf62ee1256771d3875df0d131a56fa/js/editor-effects.js#L36
```js
currentEffect === effectLevelValue.value // true
```
Забываешь про `currentEffect`, которое в твоем решении всегда указывает на актуальное название эффекта 😃

2022-07-10 13:00 UTC, AlexMasterov commented on js/editor-effects.js
> +  const createOptionsObject = (min, max, step) => ({
const createOptions`Object` = (min, max, step) => ({

**JS2**-Б9:
> В названии переменных не используется тип данных (= `object`)

2022-07-10 13:00 UTC, AlexMasterov commented on js/editor-effects.js
> +  const createOptionsObject = (min, max, step) => ({
Функция `createOptionsObject` создается заново при каждом вызове `updateSliderOptions`, что неэффективно.

2022-07-10 13:00 UTC, AlexMasterov commented on js/editor-effects.js
> +      slider.updateOptions(createOptionsObject(0, 100, 1));
Советую попробовать немного улучшить:
```diff
- slider.updateOptions(createOptionsObject(0, 100, 1));
+ slider.updateOptions(createSliderOptions({ min: 0, max: 100, step: 1 }));
```
> К сожалению, некоторые могут придраться к "числам", не вникая в код

2022-07-10 13:00 UTC, AlexMasterov commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
Подобный код потенциально нарушает критерий Д23.

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/efc15d854daf62ee1256771d3875df0d131a56fa/js/editor-effects.js#L122-L124

Советую не забывать про `currentEffect` и использовать DOM API:
```js
imgPreview.classList.remove(`effects__preview--${currentEffect}`);
if (imgPreview.classList.conains(`effects__preview--${currentEffect}`) { ... }
```

2022-07-10 13:00 UTC, AlexMasterov commented on js/editor-effects.js
> +  if (currentEffect !== 'none') {
if (currentEffect !== `'none'`) {

См. первый спойлер и замечание в https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/8#discussion_r917322546.

2022-07-10 13:01 UTC, merged

2022-07-10 13:11 UTC, webgolub commented on js/editor-effects.js
> +      imgPreview.style.filter = `grayscale(${effectLevelValue.value})`;
Так в `currentEffect` строка с названием эффекта, а в `effectLevelValue.value` числовое значение с ползунка. Или я что-то не понял?

2022-07-10 13:15 UTC, AlexMasterov commented on js/editor-effects.js
> +      imgPreview.style.filter = `grayscale(${effectLevelValue.value})`;
Точно, не к тому месту оставил замечание.

2022-07-10 13:25 UTC, webgolub commented on js/editor-effects.js
> +      slider.updateOptions(createOptionsObject(0, 100, 1));
После деструктуризации получил ошибку, вот что пишет в консоли:

```
Uncaught Error: noUiSlider: Missing 'min' or 'max' in 'range'.
    at Object.testRange [as t] (nouislider.js:564:17)
    at nouislider.js:879:23
    at Array.forEach (<anonymous>)
    at testOptions (nouislider.js:871:26)
    at Object.updateOptions (nouislider.js:2145:28)
    at updateSliderOptions (editor-effects.js:80:14)
    at resetEffects (editor-effects.js:114:3)
    at resetUploadPicture (editor.js:25:3)
    at HTMLInputElement.<anonymous> (editor.js:63:3)
```

2022-07-10 13:30 UTC, AlexMasterov commented on js/editor-effects.js
> +      slider.updateOptions(createOptionsObject(0, 100, 1));
Тебе показываю интерфейс, а реализовать нужно самому.

Времени нет, покажу пример:
```js
const createSliderOptions = ({ min, max, step }) => ({
  range: { min, max },
  start: max,
  step,
});
```

2022-07-10 13:34 UTC, webgolub commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
С  `if (currentEffect !== 'none')` всё ясно.
Но не могу понять в чём нарушение Д23. Я предварительно удаляю все классы `effects__preview--` с изображения и добавляю новый класс эффекта. В том что в removeEffectsClasses удаляю все классы с  `effects__preview--` ?

2022-07-10 13:49 UTC, AlexMasterov commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
У тебя написан код с логикой, по которой может быть добавлен только один класс. Но в этом же модуле (контексте), рядом с этой логикой, создается функция, которая про это "не знает" и через странный перебор классов и по условию с рег. выражением пытается удалить все возможные классы для фильтров.

> Всё это напоминает историю с `isNotTextFields`, в твоем первым варианте, когда вместо простого условия появилась нечитаемая функция, где в 3 (!) цикла что-то перебиралась 😃

Если коротко, то здесь вообще не нужен цикл, а следовало опереться на свою же _логику_.

Оставим это на усмотрение случайного проверяющего.

2022-07-10 13:52 UTC, AlexMasterov commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
Всё это напоминает историю с `isNotTextFields`, в твоем первом варианте, когда вместо простого условия появилась нечитаемая функция, где в 3 (!) цикла перебирались классы. Используются одни и те же подходы. Вот, что значит, привычка 😃

2022-07-10 14:15 UTC, webgolub commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
Тут, наверное, больше неопытность и вытекающая из неё большая любовь к костылям.  Я опять зачем-то решил перестраховаться и удалить все возможные (при одном реальном) классы. Ну и сделал это как мог (максимально криво).
Подскажи, пожалуйста, как проще можно удалить класс по маске?  Ведь если я просто удалю все классы - получится нарушение Д23.

2022-07-10 15:00 UTC, webgolub commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
А что значит 🚀? Что я поехавший 😃?

2022-07-11 00:35 UTC, webgolub commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
Можешь, пожалуйста, пояснить что мне нужно понять из конструкции

```
imgPreview.classList.remove(`effects__preview--${currentEffect}`);
if (imgPreview.classList.conains(`effects__preview--${currentEffect}`) { ... }
```

2022-07-11 06:20 UTC, AlexMasterov commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
> Если коротко, то здесь вообще не нужен цикл, а следовало опереться на свою же _логику_

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/ff9d67c1ceba73e8dae5d6e379d2005ad1805f77/js/editor-effects.js#L128-L130

<details>
<summary>Пример</summary>

```js
const previousEffect = currentEffect;
currentEffect = evt.target.value;

imgPreview.classList.remove(`effects__preview--${previousEffect}`);
imgPreview.classList.add(`effects__preview--${currentEffect}`);
```
</details>
<details>
<summary>Пример с коллбэком (только для ознакомления!)</summary>

```js
// editor-effects.js
effectsRadioContainer.addEventListener('change', (evt) => {
  evt.preventDefault();

  const previousEffect = currentEffect;
  currentEffect = evt.target.value;

  effectChangeCallback(currentEffect, previousEffect);
});

// editor.js
setEffectChangeHandler((currentEffect, previousEffect) => {
  imgPreview.classList.remove(`effects__preview--${previousEffect}`);
  imgPreview.classList.add(`effects__preview--${currentEffect}`);

  if (currentEffect === Effect.NONE) {
    hideSlider();
  } else {
    showSlider();
  }

  resetSlider();
});
```
</details>

2022-07-11 11:30 UTC, webgolub commented on js/editor-effects.js
> +    if(/effects__preview--/.test(item)) {element.classList.remove(item);} });
Спасибо!
Тоже вчера посетила мысль что можно сохранять предыдущий эффект.