Module11 task1
htmlacademy-javascript/2049181-kekstagram-26 pull request #9
Opened 2022-07-15 16:41 UTC by webgolub

2022-07-15 19:01 UTC, AlexMasterov requested changes

2022-07-15 19:01 UTC, AlexMasterov commented on js/api.js
> +
<details>
<summary>api.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/api.js#L3
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/api.js#L12
</details>

На защите проекта могут придраться.

[`Б 7`](https://up.htmlacademy.ru/javascript/26/criteries#b7)
> Названия констант (постоянных значений) написаны прописными (заглавными) буквами

2022-07-15 19:01 UTC, AlexMasterov commented on js/api.js
> +      showAlert('Данные с сервера не получены. Попробуйте обновить страницу');
Вызов `showAlert` в этой функции (и в этом модуле) — ошибка.

Нужно позволить задавать поведение на "ошибку" при использование функции, а не предопределять его, тем более функцией с побочным эффектом.

> Для защиты не критично

2022-07-15 19:01 UTC, AlexMasterov commented on js/big-picture.js
> +let bigPictureCloseButtonClickHandler = null;
let bigPictureCloseButtonClick`Handler` = null;

На защите проекта могут придраться.

> На JS2/3 для обработчиков событий компонентов используется формат с `handle*` (как в сообществе React), но не все наставники с JS1 учувствует на след. интенсивах и знают про это

[`Д 4`](https://up.htmlacademy.ru/javascript/26/criteries#d4)
> Из названия обработчика события и функции-колбэка следует, что это обработчик.

> Для единственного обработчика или функции можно использовать `callback` или cb

2022-07-15 19:01 UTC, AlexMasterov commented on js/big-picture.js
> +  document.addEventListener('keydown', bigPictureEscKeydownHandler);
<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/big-picture.js#L27-L29
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/big-picture.js#L65
</details>

Еще одна ошибка, но для защиты проекта не критично.

> На JS2 будет как в моем примере

2022-07-15 19:01 UTC, AlexMasterov commented on js/form.js
> +import { showSuccessUploadModal, closeSuccessUploadModal, setModalCloseButtonClickHandler, setModalWindowEscKeydownHandler, setModalWindowWrapperClickHandler, showFailUploadModal, closeFailUploadModa
```js
import { 
  showSuccessUploadModal,
  closeSuccessUploadModal,
  // ...
};
```

2022-07-15 19:01 UTC, AlexMasterov commented on js/form.js
> +  if (isEscKey(evt) & (document.body.lastChild.matches('.success'))) {
if (isEscKey(evt) `&` (document.body.lastChild.matches('.success'))) {

[`Д 9`](https://up.htmlacademy.ru/javascript/26/criteries#d9)
> Отсутствуют потенциально некорректные операции

2022-07-15 19:01 UTC, AlexMasterov commented on js/form.js
> +  } else if (isEscKey(evt)) {
if (`isEscKey(evt)`
} else if (`isEscKey(evt)`) {

Проверяется дважды.

2022-07-15 19:01 UTC, AlexMasterov commented on js/form.js
> +  const sendStatusWindow = document.querySelector('.error');
const `send`StatusWindow = document.querySelector('.error');

В название переменной используется глагол, хотя она не указывает на функцию.

[`Б 4`](https://up.htmlacademy.ru/javascript/26/criteries#b4)
> В качестве имён переменных и свойств используются английские _существительные_

2022-07-15 19:01 UTC, AlexMasterov commented on js/form.js
> +  imgUploadOverlayCancellButton.addEventListener('click', onImgUploadOverlayCancelButtonClick);
<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/big-picture.js#L65-L66
</details>

<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/form.js#L100-L101
</details>

[`Д 6`](https://up.htmlacademy.ru/javascript/26/criteries#d6)
> Используется единый стиль именования переменных

> Стиль именования переменных сохраняется _во всех_ модулях, например:

> не следует мешать обработчики содержащие `Handler` и `on`

2022-07-15 19:01 UTC, AlexMasterov commented on js/main.js
> +import './api.js';
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/main.js#L1
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/main.js#L5

Второй `import` нужно удалить.

2022-07-15 19:01 UTC, AlexMasterov commented on js/main.js
`message.js`

Пустой модуль следует удалить.

Б12

2022-07-15 19:01 UTC, AlexMasterov commented on js/picture.js
> +  onModalEscKeydown(evt);
<details>
<summary>picture.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/picture.js#L57
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/picture.js#L61
</details>

Б6 (Д4)

См. https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/6#discussion_r910483643:
> Название функции, которая используется в роли обработчика событий DOM, не должно начинаться с глагола - подобное по `Б6` требуется только для обычных функций, которые вызываются в коде

2022-07-15 19:01 UTC, AlexMasterov commented on js/util.js
> +  alertContainer.style.textAlign = 'center';
<details>
<summary>util.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/util.js#L12-L18
</details>

7x `alertContainer.style`.*

2022-07-15 19:01 UTC, AlexMasterov commented on js/window.js
> +  document.body.append(successUploadModal);
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/d275c99f80749d583463ac96e21315a89f962c58/js/window.js#L2

document.body.append(`successUploadModal`);

Обращаю внимание, что здесь элемент шаблона используется напрямую, без клонирования.

2022-07-15 19:03 UTC, AlexMasterov commented
> Files changed `19`

По задание требуется только добавить модуль для загрузки данных с сервера 😃

2022-07-15 19:50 UTC, webgolub commented on js/api.js
> +      showAlert('Данные с сервера не получены. Попробуйте обновить страницу');
Переписал показ ошибки через колбэк:
```js
const getData = async (onSuccess, onFail) => {
  try {
    const response = await fetch(GET_DATA_URL);
    const data = await response.json();
    if (!response.ok) {
      throw new Error (`${response.status} - ${response.statusText}`);
    }
    onSuccess(data);
  } catch (err) {
    onFail();
  }
};
```
В main.js вызываю так:
```js
getData(renderPictures, showAlert('Данные с сервера не получены. Попробуйте обновить страницу'));
```

Но `showAlert `срабатывает независимо от того, использую ли я вообще в `getData `параметр `onFail`. Не могу разобраться почему.

2022-07-15 20:11 UTC, webgolub commented on js/form.js
> +  if (isEscKey(evt) & (document.body.lastChild.matches('.success'))) {
Вопрос не по теме самого коммента - я опечатался и написал `& `вместо `&&` - почему условие работало? Как я понял, там был не оператор `И`, а побитовое сравнение операндов же.

2022-07-15 20:17 UTC, webgolub commented on js/window.js
> +  document.body.append(successUploadModal);
Я намеренно не клонировал, т.к. он никак не изменяется во время использования. Это неправильный подход?

2022-07-15 20:53 UTC, webgolub commented on js/big-picture.js
> +let bigPictureCloseButtonClickHandler = null;
Про handle* для обработчиков событий компонентов я понял что мой  `bigPictureCloseButtonClickHandler `должен стать `handleBigPictureCloseButtonClick` — верно?

Но не пойму где можно применить:

> Для единственного обработчика или функции можно использовать callback или cb

И следующее правило вроде тоже соблюдено:

> Из названия обработчика события и функции-колбэка следует, что это обработчик.

или я не вижу где проблема?

2022-07-15 21:41 UTC, AlexMasterov commented on js/big-picture.js
> +let bigPictureCloseButtonClickHandler = null;
> Про handle* для обработчиков событий компонентов я понял что мой bigPictureCloseButtonClickHandler должен стать handleBigPictureCloseButtonClick — верно?

Это зависит от исправления https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/9#discussion_r922435559.

Сейчас ты снова изменил именования, причем уже в проверенном коде. Но, теперь, функции на которые указывают эти переменные явно используются как _обработчики событий DOM_, а не _обработчики событий модулей_, что требует соблюдения Д4 (вместо Б6). Никаких `handle` и даже `callback`.

> С этим изменением все имена функций, которые устанавливают такие обработчики вводят в заблуждение. Говоря иначе, теперь модули стали [протекающими абстракциями](https://en.wikipedia.org/wiki/Leaky_abstraction), а свойство модульности снова утеряно

2022-07-15 21:43 UTC, AlexMasterov commented on js/api.js
> +      showAlert('Данные с сервера не получены. Попробуйте обновить страницу');
```js
getData(
  renderPictures, 
  () => {
     showAlert('Данные с сервера не получены. Попробуйте обновить страницу')
   },
);
```

2022-07-15 21:47 UTC, AlexMasterov commented on js/api.js
> +      showAlert('Данные с сервера не получены. Попробуйте обновить страницу');
> Переписал показ ошибки через колбэк

1. `if (!response.ok) { ... }` выбрасывает исключение, которое сейчас нигде не обрабатывается. Возможно, что лучше вызывать коллбэк `onFail`.
2. В коллбэки ничего полезного не передается, как например, статус и сообщение об ошибке. Сейчас они все равно никак не используются. Поэтому некритично

2022-07-15 21:56 UTC, AlexMasterov commented on js/window.js
> +  document.body.append(successUploadModal);
Элемент `successUploadModal` уже находится в DOM, но при добавление в другой узел будет склонирован (если правильно помню, но если открывается несколько раз, то всё нормально). Тогда "он никак не изменяется во время использования" вполне аргумент 😃

2022-07-15 22:26 UTC, webgolub commented on js/api.js
> +      showAlert('Данные с сервера не получены. Попробуйте обновить страницу');
Получается, место того, чтобы передать с параметром, я вызывал `showAlert`?

2022-07-15 22:53 UTC, AlexMasterov commented on js/api.js
> +      showAlert('Данные с сервера не получены. Попробуйте обновить страницу');
> Получается, место того, чтобы передать с параметром, я вызывал `showAlert`?

Да 😃

2022-07-15 23:13 UTC, AlexMasterov commented on js/form.js
> +  if (isEscKey(evt) & (document.body.lastChild.matches('.success'))) {
Оператор `if` ожидает значение булево типа и в случае другого типа сработает неявное приведение:

```js
true & true // 1
Boolean(1) // true
```

2022-07-16 01:14 UTC, AlexMasterov requested changes

2022-07-16 01:14 UTC, AlexMasterov commented on js/api.js
> +      throw new Error (`${response.status} - ${response.statusText}`);
😕

Желательно убрать `throw`, как советовал ранее.

2022-07-16 01:14 UTC, AlexMasterov commented on js/big-picture.js
> +let BigPictureEscKeydownHandler = null;
let `B`igPictureCloseButtonClickHandler = null;
let `B`igPictureEscKeydownHandler = null;

[`Б 3`](https://up.htmlacademy.ru/javascript/26/criteries#b3)
> Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации `camelCase`

2022-07-16 01:14 UTC, AlexMasterov commented on js/effects.js
> +    min: min,
Возможность подобного сокращения (ES6) была показаны в моем примере:
```diff
- min: min,
+ min,
```

2022-07-16 01:14 UTC, AlexMasterov commented on js/form.js
> +const ImgUploadOverlayCancelButtonClickHandler = (evt) => {
const `I`mgUploadOverlayCancelButtonClickHandler = (evt) => {

Б3

2022-07-16 01:14 UTC, AlexMasterov commented on js/form.js
> +const ImgUploadOverlayEscKeydownHandler = (evt) => {
const `I`mgUploadOverlayEscKeydownHandler = (evt) => {

Б3

2022-07-16 01:14 UTC, AlexMasterov commented on js/form.js
> +  const IsSendStatusWindowOpened = document.querySelector('.error');
const `I`sSendStatusWindowOpened = document.querySelector('.error');

Б3

const `IsSend`StatusWindowOpened = document.querySelector('.error');


Б4

2022-07-16 01:14 UTC, AlexMasterov commented on js/picture.js
> +const ModalEscKeydownHandler = (evt) => {
const `M`odalEscKeydownHandler = (evt) => {

Б3

2022-07-16 01:14 UTC, AlexMasterov commented on js/picture.js
> +const ModalCloseButtonClickHandler = () => {
const `M`odalCloseButtonClickHandler = () => {

Б3

2022-07-16 01:14 UTC, AlexMasterov commented on js/picture.js
> +  ModalEscKeydownHandler(evt);
См. внимательно https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/9#discussion_r922440433.

`ModalCloseButtonClickHandler`
`ModalEscKeydownHandler`

Напомню, что переменные с названием в формате _обработчика событий DOM_ нельзя вызывать, как обычную функцию. В таком случае её название должно соответствовать критерию Б6, т.е. начинаться с _глагола_.

Б6

2022-07-16 01:14 UTC, AlexMasterov commented on js/window.js
> +let onModalWindowWrapperClick = null;
let `on`ModalWindowCloseButtonClick = null;
let `on`ModalWindowEscKeydown  = null;
let `on`ModalWindowWrapperClick = null;

Нужно определиться с форматом именования (`on` или `handler`) _обработчиков событий DOM_ и использовать его _во всех_ модулях проекта.

> Не понимаю, зачем за неделю до защиты было снова менять именования обработчиков 😟

Д6

См. https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/9#discussion_r922435559:

> Стиль именования переменных сохраняется **во всех модулях**, например:

> не следует мешать обработчики содержащие `Handler` и `on`

2022-07-16 01:14 UTC, AlexMasterov commented on js/window.js
> +  successUploadModal.remove();
successUploadModal.`remove()`;

В функции `createOrRemoveWindowWrapperClickHandler` нет смысла, ведь обработчики на доч. узлах элемента `successUploadModal` удалятся вместе с ним.

2022-07-16 01:14 UTC, AlexMasterov commented on js/main.js
>  import './validate.js';
```js
import './form.js';
import './validate.js';
```

Когда здесь почему-то нужно выполнить код модуля (неявно с побочным эффектом), а в другом модуле импортировать из него пару функций, то это еще один пример, когда модульная система используется неправильно.

2022-07-16 01:14 UTC, AlexMasterov commented on js/validate.js
> +export { validate };
js/`validate`.js

```js
export { validate };
```
`validate` _чего_? 😃

2022-07-16 01:14 UTC, AlexMasterov commented on js/form.js
> +  if (evt.target.className === 'success__button') {
setModalCloseButtonClickHandler ((`evt`) => {

Грубая ошибка проектирования и использование коллбэков.

2022-07-16 01:14 UTC, AlexMasterov commented on js/effects.js
> +  imgPreview.classList.remove(`effects__preview--${currentEffect}`);
const removeEffectsClasse`s` = () => {
  imgPreview.classList.remove(`effects__preview--${currentEffect}`);

Функция в своем название "обещает" удалить классы (во множ. числе), но на деле удаляет только один 😃

2022-07-16 01:14 UTC, AlexMasterov commented on js/big-picture.js
> +  BigPictureEscKeydownHandler = callback;
const setBigPicture`EscKeydown`Handler = (callback) => {

Такая функция теперь просто устанавливает (`set`) пользовательский коллбэк как _обработчик события DOM_ для `keydown`, который будет срабатывать при любом нажатие на клавишу. Никакого срабатывания на `Esc` здесь больше нет — реализация этой логики теперь остается за пользователем такой функции, но это неочевидно по названию, а сам интерфейс является протекающей абстракцией.

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/01d139e06e830b9f55e6c0cb8f04dc8d10d65cf5/js/big-picture.js#L66

> Такая функция теперь просто _устанавливает_ (`set`) <...>

```js
setBigPictureEscKeydownHandler(() => console.log('handler 1'));
// showBigPicture()
setBigPictureEscKeydownHandler(() => console.log('handler 2'));
```
Теперь для события `keydown` будет установлены _два_ разных обработчика, т.е. такая функция теперь не устанавливает, а _добавляет_ обработчики. И всё это вообще неявно для пользователя функции 😃

2022-07-16 10:21 UTC, webgolub commented on js/effects.js
> +    min: min,
Не совсем понимаю как работает данное сокращение.
Ну, то есть мы передаём аргументы как объект и в функции они сразу подставляются в нужные места как `ключ: значение` - это я вижу.
Меня смущает функция возвращает объект с вложенным объектом, а в аргументы мы передаём `одномерный ` объект и всё подставляется в нужные места.

2022-07-16 10:28 UTC, webgolub commented on js/picture.js
> +const ModalCloseButtonClickHandler = () => {
Блин, прости мою рассеянность и излишнюю активность с переименованием проверенных модулей

2022-07-16 10:57 UTC, webgolub commented on js/main.js
>  import './validate.js';
Да, тут снова моя невнимательность и хвосты от предыдущих реализаций

2022-07-16 11:19 UTC, webgolub commented on js/form.js
> +  if (evt.target.className === 'success__button') {
Я таким образом пытался уйти от нарушения [Д26](https://up.htmlacademy.ru/profession/react/10/javascript/26/criteries#d23).
Опиши, пожалуйста, в чём заключается ошибка.  В том что передаётся весь объект события, а не одно его нужное свойство или в том что вообще проверка с участием объекта события производится не «под капотом» модуля, где этот коллбэк будет вызываться?

2022-07-16 11:45 UTC, webgolub commented on js/big-picture.js
> +  BigPictureEscKeydownHandler = callback;
С первой частью комментария всё понятно. Я перенёс проверку нажатой клавиши внутрь модуля:
```js
const setBigPictureEscKeydownHandler = (callback) => {
  bigPictureEscKeydownHandler = (evt) => {
    if (isEscKey(evt)){
      evt.preventDefault();

      callback();
    }
  };
};
```

А тут не пойму 

> Теперь для события keydown будет установлены два разных обработчика, т.е. такая функция теперь не устанавливает, а добавляет обработчики. И всё это вообще неявно для пользователя функции 😃

почему будут установлены два обработчика? Ты имеешь ввиду что если два раза  вызвать функцию, то будут добавлены два обработчика? Но как, если функция только присваивает переменной код функции, но не добавляет обработчик? Я завис.

2022-07-16 13:31 UTC, AlexMasterov commented on js/big-picture.js
> +  BigPictureEscKeydownHandler = callback;
> Ты имеешь ввиду что если два раза вызвать функцию, то будут добавлены два обработчика? Но как

См. внимательно пример https://github.com/htmlacademy-javascript/2049181-kekstagram-26/pull/9#discussion_r922595075.

<details>
<summary>big-picture.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/01d139e06e830b9f55e6c0cb8f04dc8d10d65cf5/js/big-picture.js#L32-L34
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/01d139e06e830b9f55e6c0cb8f04dc8d10d65cf5/js/big-picture.js#L59-L67
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/01d139e06e830b9f55e6c0cb8f04dc8d10d65cf5/js/big-picture.js#L79-L84
</details>

Если между установками обработчика (`setBigPictureEscKeydownHandler `) показывать большое изображение (`showBigPicture`), то на `document` для события `keydown` будут накапливаться обработчики. При этом функция `showBigPicture` экспортируется и тем самым является публичной. Можешь проверить.

В модуле уровнем выше, _пользователю_ (клиенту) этой функции нужно знать тайну порядка вызова этих методов, т.е. внутренние детали реализации модуля, так? 😃

2022-07-16 13:42 UTC, AlexMasterov commented on js/form.js
> +  if (evt.target.className === 'success__button') {
Вынос обработчиков — это не цель, а _средство_ достижение определенный свойств кода. Причем, организация сообщения между модулей разных уровней на основе коллбэков — простая (базовая) концепция. После новой переделки публичные интерфейсы модулей как абстракции сломались и своим названием "обманывают". В таком подходе модульность снова пропала 😃

> В том что передаётся весь объект события, а не одно его нужное свойство или в том что вообще проверка с участием объекта события производится не «под капотом» модуля, где этот коллбэк будет вызываться?

Если оценивать только реализацию, код в этом месте, то ты верно подметил. Абстракции здесь явно созданы не на пользу клиента, т.е. пользователя этого кода в другом модуле. Они обманывают в своем название и нагружают клиента деталями реализации.

2022-07-16 13:46 UTC, AlexMasterov commented on js/effects.js
> +    min: min,
Такая возможность сокращение позволяет использовать название переменной (на этапе парсинга кода движком они называются индефикаторами) в качестве названия ключа объекта. Тогда значение на которое указывает переменная станет значением ключа объекта.

В свое время эту возможность очень ждали.

2022-07-16 14:56 UTC, webgolub commented on js/form.js
> +  if (evt.target.className === 'success__button') {
Подскажи, допустимо ли в данном случае  использовать два разных обработчика для кликов по кнопкам закрытия разных окон? Тогда условие проверять не надо, но у `big-picture.js `будет на одну публичную функцию больше.

2022-07-16 15:14 UTC, webgolub commented on js/big-picture.js
> +  BigPictureEscKeydownHandler = callback;
> Если между установками новой функции-обработчика (setBigPictureEscKeydownHandler ) показывать большое изображение (showBigPicture), то на documentдля событияkeydownбудут накапливаться обработчики. При этом функцияshowBigPicture` экспортируется и тем самым является публичной. В модуле уровнем выше, пользователю (клиенту) этой функции нужно знать тайну порядка вызова этих функций, т.е. внутренние детали реализации модуля, так? 😃

Всё так. 😔 С точки зрения организации модульности у меня всё стабильно ужасно. 
Но такой сценарий невозможен в текущей реализации работы приложения, ведь перед показом нового большого изображения всегда либо закроется старое, либо перезагрузится страница, и предыдущий обработчик будет снят. Хотя, я понял что модуль должен предоставлять API, который не допускает такого неявного поведения.

> Теперь для события keydown будет установлены два разных обработчика, т.е. такая функция теперь не устанавливает, а добавляет обработчики. И всё это вообще неявно для пользователя функции 😃

А разве `setBigPictureEscKeydownHandler` не устанавливает обработчик `bigPictureEscKeydownHandler`, который уже добавляется к событию?

2022-07-16 15:16 UTC, AlexMasterov commented on js/form.js
> +  if (evt.target.className === 'success__button') {
Допустимо.

> Я не преследовал цели вынести обработчики, таким образом я пытался обойти проблему использования функции до её объявления

В случае окна с сообщением, у которого нет интерактивности, можно было всем эти не заморачиваться. 

<details>
<summary>Пример</summary>

```js
const successMessageTemplateElement = document.querySelector('#success').content.querySelector('.success');
const errorMessageTemplateElement = document.querySelector('#error').content.querySelector('.error');

const showMessage = (type) => {
  const templateElement = type === 'success'
    ? successMessageTemplateElement
    : errorMessageTemplateElement;

  const messageElement = templateElement.cloneNode(true);
  const messageBlockElement = messageElement.querySelector(`.${type}__inner`);

  const remove = () => {
    messageElement.remove();
    document.removeEventListener('click', onClick);
  };

  function onClick(evt) {
    // ...
    remove();
  }

  document.body.append(messageElement);

  document.addEventListener('click', onClick);
};

const showSuccessMessage = () => showMessage('success');
const showErrorMessage = () => showMessage('error');
```
</details>

Пример с коллбэком сложней, поскольку элемент окна с сообщением требуется добавлять и удалять, а не просто скрывать и показывать. Если будет время, то набросаю пример.

2022-07-16 16:01 UTC, webgolub commented on js/form.js
> +  if (evt.target.className === 'success__button') {
Хм, то есть я могу просто `closeSuccessUploadModal `и `closeFailUploadModal` объявить с помощью function declaration и тогда из модуля `window.js` экспортирую только `showSuccessUploadModal `и `showFailUploadModal`.
Или исключения с function declaration разрешаются только лишь для обработчиков событий?

2022-07-16 16:13 UTC, AlexMasterov commented on js/form.js
> +  if (evt.target.className === 'success__button') {
> и тогда из модуля window.js экспортирую только showSuccessUploadModal и showFailUploadModal

Да, чтобы уже скорее перейти к след. заданию. Времени мало.

> Или исключения с function declaration разрешаются только лишь для обработчиков событий?

Можешь объявлять через `function declaration`, когда требуется угомонить линтер.

Необходимость в таком объявление не всегда указывает на проблемы с распределением ответственностью между функциям и модулями. Нужно разбираться в каждом случае.

2022-07-17 10:42 UTC, webgolub commented on js/big-picture.js
> +  BigPictureEscKeydownHandler = callback;
На случай, если уведомление могло затеряться, спрошу ещё раз - можно ли оставлять как есть в моём случае и отправлять домашку на проверку через интерфейс `htmlacademy`?

2022-07-17 11:12 UTC, AlexMasterov commented on js/big-picture.js
> +  BigPictureEscKeydownHandler = callback;
Отправляй.

2022-07-17 14:24 UTC, AlexMasterov approved these changes

2022-07-17 14:24 UTC, AlexMasterov commented on js/form.js
> +  if (isEscKey(evt) && isNotTextFields(evt) && !isSendStatusWindowOpened) {
const `isSend`StatusWindowOpened = document.querySelector('.error');

Не исправлено.

Чтобы сохранить `is` в название:
```diff
- const isSendStatusWindowOpened = document.querySelector('.error');
+ const isErrorWindowOpened = document.querySelector('.error') !== null;
```
```diff
- if (isEscKey(evt) && isNotTextFields(evt) && !isSendStatusWindowOpened) {
+ if (isEscKey(evt) && isNotTextFields(evt) && isErrorWindowOpened) {
```

> Также обращаю внимание, что если условия `isEscKey` и `isNotTextFields` не сработают, то преждевременный поиск элемента в DOM (браузере) окажется избыточным

2022-07-17 14:24 UTC, AlexMasterov commented on js/window.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/179401566-349e8468-f794-47bd-a61d-da0346c4dee2.png)
![image](https://user-images.githubusercontent.com/700213/179402495-68315dbc-934d-4520-b4aa-b91e46283da4.png)

</details>

При отправке фото в отсутствие сети (или неправильного адреса) показывается сообщение об успешной загрузки, а за ним другое, которое уже не закрыть по `Esc`. При этом форма загрузки закрывается.

Нужно оставить одно сообщение и привести остальную логику в соответствие с ТЗ.

2022-07-17 14:24 UTC, AlexMasterov commented on js/window.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/179401566-349e8468-f794-47bd-a61d-da0346c4dee2.png)

![image](https://user-images.githubusercontent.com/700213/179401892-67431022-12bd-4402-8bdf-0434c3fb63ae.png)

</details>

См. ТЗ:
> Сообщение должно исчезать после нажатия на кнопку `.success__button`, по нажатию на клавишу `Esc` и по клику на произвольную область экрана _за пределами блока с сообщением_

Предупреждаю, что на защите проекта верстальщики и разработчики под "блоком с сообщением" понимают разное. Для верстальщика это чаще всего CSS-блок: `.success__inner`, `.error_inner` (или даже `.success__text`,  `.error__text`), а для разработчика визуальный блок, что видит пользователь, а какие у него границы узлов DOM уже вторично.

На защите проекта по JS1 в основном проверяют верстальщики и к твоему решению скорее всего придерутся 😟

2022-07-17 14:24 UTC, AlexMasterov commented on js/window.js
> +  const windowFailWrapper = document.querySelector('.error');
document.body.append(`failUploadModal`);
const `windowFailWrapper` = document.querySelector('.error');

```j
failUploadModal === windowFailWrapper // true
```

Это один и тот же элемент. Он уже есть в замыкание, можно продолжать использовать.

> Поиск в DOM (браузере) избыточен

2022-07-17 14:24 UTC, AlexMasterov commented on js/window.js
> +  document.body.classList.add('modal-open');
CSS-класс `modal-open` решает проблему с двойным ползунком для скролла, который (из-за особенности верстки) появляется у попапа с большим изображением.

Для окна с сообщением об успехе и ошибки этого не требуется, в том числе по ТЗ.

2022-07-17 14:24 UTC, AlexMasterov commented on js/window.js
> +
См. ТЗ:
> Если при отправке данных произошла ошибка запроса, нужно показать соответствующее сообщение. Разметку сообщения, которая находится в блоке #error внутри шаблона template, нужно разместить перед закрывающим тегом `</body>`. Сообщение должно исчезать после нажатия на кнопки `.error__button`, по нажатию на клавишу `Esc` и по клику на произвольную область экрана за пределами блока с сообщением. **В таком случае вся введённая пользователем информация сохраняется, чтобы у него была возможность отправить форму повторно**

Не реализовано.

> Потребуется в след. задание

2022-07-17 14:24 UTC, AlexMasterov commented on js/form.js
> +      unblockSubmitButton();
<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/49e1819d5bd2a8a1fe754c972289c6f0eb37fbbb/js/form.js#L98
https://github.com/htmlacademy-javascript/2049181-kekstagram-26/blob/49e1819d5bd2a8a1fe754c972289c6f0eb37fbbb/js/form.js#L106
</details>

См. [Promise.p.`finally`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally).

2022-07-17 14:26 UTC, merged

2022-07-17 17:32 UTC, webgolub commented on js/window.js
> +
Ничего не пойму, у меня вроде работает: https://youtu.be/cJBZznVlYjo

2022-07-17 18:02 UTC, webgolub commented on js/form.js
> +  if (isEscKey(evt) && isNotTextFields(evt) && !isSendStatusWindowOpened) {
> Чтобы сохранить is в название...

Здесь `is` нельзя использовать потому  что в выражении нет никакого сравнения, а просто найденный элемент?
И допустимо ли тогда вообще не добавлять в название переменной `is` и в условии написать, например, `if (errorWindow)`?

> ...преждевременный поиск элемента в DOM (браузере) окажется избыточным

Так сделать можно же?
```js
if (isEscKey(evt) && isNotTextFields(evt)) {
    const isErrorWindowClosed = document.querySelector('.error') === null;
    if (isErrorWindowClosed) {
      evt.preventDefault();
      resetUploadPicture();
      closeUploadOverlay();
    }
  }
```

2022-07-17 18:09 UTC, webgolub commented on js/window.js
> +
Не могу воспроизвести эту ошибку. У меня в Chrome и Firefox при отсутствии сети или неправильном адресе (изменяю в `api.js`) показывается только окно ошибки загрузки файла, при этом оно поверх формы загрузки, и данные в форме сохраняются при закрытии окна.

2022-07-17 18:37 UTC, webgolub commented on js/window.js
> +
Блин, очень сложно въехать в эти различия. Т.е. padding, которым заданы внутренние отступы и который визуально делает окно больше чем изначальный элемент с классом .success__inner не считается как часть div'a?
А как мне определять область вне блока с сообщением - `evt.target.className !== 'success_inner'` - так можно?

2022-07-17 18:54 UTC, webgolub commented on js/window.js
> +  document.body.classList.add('modal-open');
> Вроде про это объясняют в одном из заданий

Этого не видел. Добавил этот класс к body, когда увидел что под попапом можно скроллить страничку 😀.
В ТЗ нет - значит убираю, конечно.

2022-07-17 19:02 UTC, webgolub commented on js/form.js
> +      unblockSubmitButton();
А с async/await можно использовать? Нагуглил такой вариант, жизнеспособен ли он:
```js
try {
//code
} catch {
//error
} finally {
//code
}

```

2022-07-17 19:10 UTC, AlexMasterov commented on js/window.js
> +
Студенты, которые приходят на этот интенсива после верстки чаще тоже под "_блоком_ с сообщением" понимают CSS-_блок_, ведь про него столько говорили ранее, а кто его не проходил, то те визуальный блок (или блок с текстом) и в разметки просто ищут его границы.

> А как мне определять область вне блока с сообщением - `evt.target.className !== 'success_inner'` - так можно?

Да, но нужно так же не закрывать окно по клику "блок" с классом `success_title`.

2022-07-17 19:14 UTC, AlexMasterov commented on js/window.js
> +
В этом PR в остатке есть связанные замечания.
На основе PR для след. задания перепроверю получше.

2022-07-17 19:18 UTC, AlexMasterov commented on js/window.js
> +
Проверял по коммиту #49e1819d5bd2a8a1fe754c972289c6f0eb37fbbb.

Не переживай, разберемся.

2022-07-17 19:21 UTC, AlexMasterov commented on js/form.js
> +      unblockSubmitButton();
Да.

2022-07-17 19:24 UTC, AlexMasterov commented on js/form.js
> +  if (isEscKey(evt) && isNotTextFields(evt) && !isSendStatusWindowOpened) {
> Здесь `is` нельзя использовать потому что в выражении нет никакого сравнения, а просто найденный элемент?

Да, могут справедливо придраться по критериям (и вне их).

`is`, `check`, `test` и т.п., обычно указывают на предикаты (мат.) с булевым значением: `true` или `false`.

2022-07-17 19:31 UTC, AlexMasterov commented on js/window.js
> +  document.body.classList.add('modal-open');
Если ТЗ не запрещает, то может это добавить от себя.

2022-07-17 20:37 UTC, webgolub commented on js/window.js
> +
Я вёрстку не проходил и немного завис на этом моменте.
Так сделать не проблема:
```js
if (evt.target.className !== 'success__inner' &&
      evt.target.className !== 'success__title')
```
А вот как можно использовать Element.closest — не могу придумать 😖

2022-07-17 23:19 UTC, AlexMasterov commented on js/window.js
> +
Пример:
```js
if (evt.target.containts('.error__inner')) {
  closeFailUploadModal();
}
```

2022-07-18 04:58 UTC, webgolub commented on js/window.js
> +
Для экспериментов добавил в обработчик `errorWindowWrapperClickHandler` 
вывод `console.log(evt.target.contains('.error__inner'));`

Но в консоли получаю 
```
Uncaught TypeError: Failed to execute 'contains' on 'Node': parameter 1 is not of type 'Node'.
    at HTMLElement.errorWindowWrapperClickHandler (window.js:42:31)
errorWindowWrapperClickHandler @ window.js:42
```
Судя по перводу - элемент, на котором я применяю метод не является `Node`. Но как это возможно, если он отображается на странице? Если я склонирую окно ошибки, на нём та же ошибка в консоли.